# Generated by Django 5.0.3 on 2024-03-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000000)),
                ('notes_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('reference_text', models.CharField(max_length=10000)),
                ('notes_text', models.CharField(max_length=10000)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.article')),
            ],
        ),
    ]
