# Generated by Django 5.0.3 on 2024-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='create_user',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notes',
            name='reference_text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
